services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Lux\:
    resource: '../Classes/*'

  In2code\Lux\Domain\Repository:
    public: true

  dashboard.widgets.luxPageVisitsWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxPageVisitsDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxPageVisits'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxpagevisits.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxpagevisits.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxDownloadsWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxDownloadsDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxDownloads'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxdownloads.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxdownloads.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxNewsWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxNewsDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxNews'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxnews.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxnews.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxSearchtermsWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxSearchtermsDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxSearchterms'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxsearchterms.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxsearchterms.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxIdentifiedWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxIdentifiedDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'LuxIdentified'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxidentified.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxidentified.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'small'

  dashboard.widgets.LuxIdentifiedPerMonthWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxIdentifiedPerMonthDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'LuxIdentifiedPerMonth'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxidentifiedpermonth.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxidentifiedpermonth.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxRecurringWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxRecurringDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxRecurring'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxrecurring.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxrecurring.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'small'

  dashboard.widgets.LuxPageVisitsWeekWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxPageVisitsWeekDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxPageVisitsWeek'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxpagevisitsweek.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxpagevisitsweek.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxDownloadsWeekWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxDownloadsWeekDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxDownloadsWeek'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxdownloadsweek.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.luxdownloadsweek.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxReferrerWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxReferrerDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxReferrer'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.referrer.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.referrer.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'medium'

  dashboard.widgets.LuxBrowserWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxBrowserDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxBrowser'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.browser.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.browser.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'small'

  dashboard.widgets.LuxHottestLeadsWidget:
    class: 'TYPO3\CMS\Dashboard\Widgets\ListWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@In2code\Lux\Widgets\DataProvider\LuxHottestLeadsDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'luxHottestLeads'
        groupNames: 'luxgroup'
        title: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.hottestleads.title'
        description: 'LLL:EXT:lux/Resources/Private/Language/locallang_db.xlf:module.dashboard.widget.hottestleads.description'
        iconIdentifier: 'extension-lux-turquoise'
        height: 'medium'
        width: 'small'
